import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";

import Header from '@/components/Header/Header'
import Footer from '@/components/Footer'

import { ChatWidget } from '@/components/chat-widget';
import { ContactWidget } from '@/components/contact-widget'


import favicon from '@/assets/fav1.png'
import { MobileNavs } from "@/components/mobile-nav";

import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { AuthProvider } from "./AuthContext";
import { OAuth2RedirectHandler } from "./(auth)/_components/OAuth2RedirectHandler";

const inter = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "West Can Auto Parts",
  description: "Generated by create next app",
  icons: {
    icon: './fav4.png'
  }
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  return (
    <html lang="en">
      <body className={inter.className}>
      
      <AuthProvider>
      <OAuth2RedirectHandler>
        <Header />
        {children}
        <ContactWidget />
        <ChatWidget />
        <Footer />
        <MobileNavs/>
        </OAuth2RedirectHandler>
        </AuthProvider>
        
      </body>
    </html>
  );
}
