import React from 'react'

import {PageHeading} from '@/components/page-heading'

export const metadata = {
  title: "Find Replacement Parts",
  description: "Generated by create next app",
  icons:{
    icon:'./fav4.png'
  }
};


const layout = ({children}) => {
  return (
    <section className='bg-gray-100/50 py-2 md:py-4'>
        {/* <PageHeading siteTitle={"Shop"}/> */}
        {children}
    </section>
  )
}

export default layout